on: push
name: Dart Formatting
jobs:
  dartfmt:
    name: Dart Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - uses: bltavares/actions/dartfmt@master
      with:
        args: "autofix"
      env:
        GITHUB_TOKEN: "${{ secrets.TOKEN }}"
